// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChK-L4-5rx90I0RZlGde_21JhaZJB-Yw0',
    appId: '1:818429780923:android:4fa92457fbb57f34bdda9e',
    messagingSenderId: '818429780923',
    projectId: 'login-beec5',
    databaseURL: 'https://login-beec5.firebaseio.com',
    storageBucket: 'login-beec5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBar0aGyk94PCa7dX9XuDCmXFEzfft2H7U',
    appId: '1:818429780923:ios:b0b222639e4071d1bdda9e',
    messagingSenderId: '818429780923',
    projectId: 'login-beec5',
    databaseURL: 'https://login-beec5.firebaseio.com',
    storageBucket: 'login-beec5.appspot.com',
    androidClientId: '818429780923-jpi4cdv2hk7bhnn78da0aouah5vbuo95.apps.googleusercontent.com',
    iosClientId: '818429780923-vjo34acidleheov3ufe3it8572437uoi.apps.googleusercontent.com',
    iosBundleId: 'com.sportable.restaurant',
  );
}
